import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import SessionProvider from "./(features)/auth/_components/SessionProvider"
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin"
import { extractRouterConfig } from "uploadthing/server"
import { ourFileRouter } from "@/app/api/uploadthing/core"
import { CartProvider } from "./(features)/cart/_context/CartProvider"
import { NuqsAdapter } from "nuqs/adapters/next/app"
import ConditionalLayout from "@/components/layout/ConditionalLayout"
import Header from "@/components/layout/Header"
import Footer from "@/components/layout/Footer"

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <NextSSRPlugin
            /**
             * The `extractRouterConfig` will extract **only** the route configs
             * from the router to prevent additional information from being
             * leaked to the client. The data passed to the client is the same
             * as if you were to fetch `/api/uploadthing` directly.
             */
            routerConfig={extractRouterConfig(ourFileRouter)}
          />
          <NuqsAdapter>
            <CartProvider>
              <ConditionalLayout header={<Header />} footer={<Footer />}>
                {children}
              </ConditionalLayout>
            </CartProvider>
          </NuqsAdapter>
        </SessionProvider>
      </body>
    </html>
  )
}
